
# SEO settings
title: Idarlington
stylished_title: Idarlington
description: "Random thougths and TILs."
keywords: "TIL, web, coding, scala, javascript"
url: "https://idarlington.github.io"
baseurl: ""

google_analytics: UA-50842645-1
disqus_shortname: "idarlington"

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

paginate: 5
paginate_path: "/page/:num/"
comments: true

#source: source
destination: _site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed

# Author settings
author:
  name     : IKenna D. Ogbajie
  job      : Software Engineer
  thumb    : https://en.gravatar.com/userimage/42626876/ff31b74f207c61cc9d2d1d9196fd0080.jpg?size=120
  email    : iogbajie@gmail.com
  url      : http://idarlington.github.io
  github   : http://github.com/idarlington
  twitter  : http://twitter.com/idarlington

project:
    repo: https://github.com/idarlington.github.io
    name: idarlington.github.io
    author: Ikenna Ogbajie

gems:
  - jekyll-paginate
  - jekyll-sitemap

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
